### PR TITLE
Create ADR about Desktop Glean instrumentation

### PR DESCRIPTION
**Pull request by travis79**
This describes the decision on how to instrument Nimbus Desktop with Glean

### CODE REVIEW

**Comment by jaredlockhart** [comment]
Thank you for writing this up @travis79! This will be super helpful to keep around as a record.  Is it possible to actually include the structures of the individual telemetry events with their related payloads for each of the cases so it's clearer to see the differences between Legacy Desktop/Mobile Glean/Possible Desktop Glean? 🙏

**Comment by travis79** [comment]
> Thank you for writing this up @travis79! This will be super helpful to keep around as a record. Is it possible to actually include the structures of the individual telemetry events with their related payloads for each of the cases so it's clearer to see the differences between Legacy Desktop/Mobile Glean/Possible Desktop Glean? 🙏

Absolutely!  I'll add something that describes both the legacy and Glean structures to help show the mapping of data from one to the other.

**Review by danielkberry — APPROVED** [review]
Totally agree with the decision to unify the telemetry, that will be very convenient once it's in place. I don't believe there would be any data science impacts as we're not changing the meaning or timing of any of the telemetry events, just the collection method. 

As part of this change, can we add the telemetry method/source to the Experimenter API (i.e., the telemetry method that that particular experiment used)? That would make it a lot easier for Jetstream to figure out which telemetry source to use.

**Review by scholtzan — APPROVED** [review]
Sounds good to me 👍

**Review by jaredlockhart — APPROVED** [review]
Perfect thank you for adding the detailed structure.  I think this looks exactly correct and supports more of our upcoming monitoring goals.  Thank you @danielkberry and @scholtzan for weighting in and @travis79 for putting this together 🙏

**Pull request merged**
